### ISSUE TITLE
Pi is not using the full capacity of the SD card

### ISSUE THREAD

**Issue by tolgaijin** [maltewirz/donkeycar#4]
https://github.com/wroscoe/donkey/blob/master/docs/guide/install_software.md

`Note: If you are using the prebuilt image specified above, your Pi is not using the full capacity of the SD card. To make the full capacity accessible, SSH into the Pi and run sudo raspi-config to go into the configuration tool. Select 7 Advanced Options and A1 Expand Filesystem. And then select <Finish> to exit the configuration tool and reboot. The Pi can access the full capacity of the SD card now.
`

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by FranzDayo** [comment]
Done
